name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
      steps:
        - name: Print Message
          run: echo "Hello World!\nWelcome to the world of GitHub"
        - name: Print Hostname
          run: hostname
