name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world\nWelcome to the world of DevOps"
      - name: Print Hostname
        run: hostname
      - name: Print Goodbye
        run: echo "Thank You! Goodbye!"
